name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_jar:
    name: Build JAR
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: careassistant
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set DB connection env
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/careassistant" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=postgres" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=postgres" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test

      - name: Upload jar as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ms-users-0.0.1.jar
          path: target/ms-users-0.0.1.jar
          retention-days: 1
